server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: chatapp
  datasource:
    url: {DATASOURCE_URL}
    username: {DATASOURCE_USERNAME}
    password: {DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signer-key: {JWT_SIGNER_KEY}